/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefsIndexRouteImport } from './routes/briefs/index'
import { Route as BriefsIdRouteImport } from './routes/briefs/$id'

const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefsIndexRoute = BriefsIndexRouteImport.update({
  id: '/briefs/',
  path: '/briefs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefsIdRoute = BriefsIdRouteImport.update({
  id: '/briefs/$id',
  path: '/briefs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/signals': typeof SignalsRoute
  '/briefs/$id': typeof BriefsIdRoute
  '/briefs/': typeof BriefsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/signals': typeof SignalsRoute
  '/briefs/$id': typeof BriefsIdRoute
  '/briefs': typeof BriefsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/signals': typeof SignalsRoute
  '/briefs/$id': typeof BriefsIdRoute
  '/briefs/': typeof BriefsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new' | '/signals' | '/briefs/$id' | '/briefs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new' | '/signals' | '/briefs/$id' | '/briefs'
  id: '__root__' | '/' | '/new' | '/signals' | '/briefs/$id' | '/briefs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  SignalsRoute: typeof SignalsRoute
  BriefsIdRoute: typeof BriefsIdRoute
  BriefsIndexRoute: typeof BriefsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs/': {
      id: '/briefs/'
      path: '/briefs'
      fullPath: '/briefs/'
      preLoaderRoute: typeof BriefsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs/$id': {
      id: '/briefs/$id'
      path: '/briefs/$id'
      fullPath: '/briefs/$id'
      preLoaderRoute: typeof BriefsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  SignalsRoute: SignalsRoute,
  BriefsIdRoute: BriefsIdRoute,
  BriefsIndexRoute: BriefsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
