/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesIndexRouteImport } from './routes/sources/index'
import { Route as BriefsIndexRouteImport } from './routes/briefs/index'
import { Route as SourcesSearchRouteImport } from './routes/sources/search'
import { Route as BriefsIdRouteImport } from './routes/briefs/$id'
import { Route as SourcesRunsIndexRouteImport } from './routes/sources/runs/index'
import { Route as SourcesRunsIdRouteImport } from './routes/sources/runs/$id'

const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefsIndexRoute = BriefsIndexRouteImport.update({
  id: '/briefs/',
  path: '/briefs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSearchRoute = SourcesSearchRouteImport.update({
  id: '/sources/search',
  path: '/sources/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefsIdRoute = BriefsIdRouteImport.update({
  id: '/briefs/$id',
  path: '/briefs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRunsIndexRoute = SourcesRunsIndexRouteImport.update({
  id: '/sources/runs/',
  path: '/sources/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRunsIdRoute = SourcesRunsIdRouteImport.update({
  id: '/sources/runs/$id',
  path: '/sources/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/signals': typeof SignalsRoute
  '/briefs/$id': typeof BriefsIdRoute
  '/sources/search': typeof SourcesSearchRoute
  '/briefs/': typeof BriefsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/sources/runs/$id': typeof SourcesRunsIdRoute
  '/sources/runs/': typeof SourcesRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/signals': typeof SignalsRoute
  '/briefs/$id': typeof BriefsIdRoute
  '/sources/search': typeof SourcesSearchRoute
  '/briefs': typeof BriefsIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/sources/runs/$id': typeof SourcesRunsIdRoute
  '/sources/runs': typeof SourcesRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/signals': typeof SignalsRoute
  '/briefs/$id': typeof BriefsIdRoute
  '/sources/search': typeof SourcesSearchRoute
  '/briefs/': typeof BriefsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/sources/runs/$id': typeof SourcesRunsIdRoute
  '/sources/runs/': typeof SourcesRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/signals'
    | '/briefs/$id'
    | '/sources/search'
    | '/briefs/'
    | '/sources/'
    | '/sources/runs/$id'
    | '/sources/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/signals'
    | '/briefs/$id'
    | '/sources/search'
    | '/briefs'
    | '/sources'
    | '/sources/runs/$id'
    | '/sources/runs'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/signals'
    | '/briefs/$id'
    | '/sources/search'
    | '/briefs/'
    | '/sources/'
    | '/sources/runs/$id'
    | '/sources/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  SignalsRoute: typeof SignalsRoute
  BriefsIdRoute: typeof BriefsIdRoute
  SourcesSearchRoute: typeof SourcesSearchRoute
  BriefsIndexRoute: typeof BriefsIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
  SourcesRunsIdRoute: typeof SourcesRunsIdRoute
  SourcesRunsIndexRoute: typeof SourcesRunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs/': {
      id: '/briefs/'
      path: '/briefs'
      fullPath: '/briefs/'
      preLoaderRoute: typeof BriefsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/search': {
      id: '/sources/search'
      path: '/sources/search'
      fullPath: '/sources/search'
      preLoaderRoute: typeof SourcesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs/$id': {
      id: '/briefs/$id'
      path: '/briefs/$id'
      fullPath: '/briefs/$id'
      preLoaderRoute: typeof BriefsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/runs/': {
      id: '/sources/runs/'
      path: '/sources/runs'
      fullPath: '/sources/runs/'
      preLoaderRoute: typeof SourcesRunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/runs/$id': {
      id: '/sources/runs/$id'
      path: '/sources/runs/$id'
      fullPath: '/sources/runs/$id'
      preLoaderRoute: typeof SourcesRunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  SignalsRoute: SignalsRoute,
  BriefsIdRoute: BriefsIdRoute,
  SourcesSearchRoute: SourcesSearchRoute,
  BriefsIndexRoute: BriefsIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
  SourcesRunsIdRoute: SourcesRunsIdRoute,
  SourcesRunsIndexRoute: SourcesRunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
